// lib/storageKeys.ts — Centralized storage key constants for chrome.storage.local

export const SK = {
  CONFIG: 'hchat:config',
  CONFIG_AWS: 'hchat:config:aws',
  CONV_PREFIX: 'hchat:conv:',
  CONV_INDEX: 'hchat:conv-index',
  BOOKMARKS: 'hchat:bookmarks',
  USAGE: 'hchat:usage',
  PLUGINS: 'hchat:plugins',
  MESSAGE_QUEUE: 'hchat:message-queue',
  SEARCH_INDEX: 'hchat:search-index',
  SEARCH_INDEX_VERSION: 'hchat:search-index-version',
  SEARCH_CACHE_PREFIX: 'hchat:search-cache:',
  ASSISTANTS: 'hchat:assistants',
  ACTIVE_ASSISTANT: 'hchat:active-assistant',
  DOC_PROJECTS: 'hchat:doc-projects',
  DOC_PROJECT_PREFIX: 'hchat:doc-project:',
  DOC_TEMPLATES: 'hchat:doc-templates',
  CHAT_TEMPLATES: 'hchat:chat-templates',
  GUARDRAIL_CONFIG: 'hchat:guardrail-config',
  USER_PREFS: 'hchat:user-prefs',
  CONV_SUMMARIES: 'hchat:conv-summaries',
  ASSISTANT_CHAINS: 'hchat:assistant-chains',
  PROMPT_CACHE: 'hchat:prompt-cache',
  AI_MEMORIES: 'hchat:ai-memories',
  RESPONSE_STYLES: 'hchat:response-styles',
  WORKFLOWS: 'hchat:workflows',
  MCP_SERVERS: 'hchat:mcp-servers',
  AUDIT_LOG: 'hchat:audit-log',
  POLICIES: 'hchat:policies',
  POLICY_STATUS: 'hchat:policy-status',
  SHARE_HISTORY: 'hchat:share-history',
  SHARED_ITEMS: 'hchat:shared-items',
  PAGE_CONTEXT: 'hchat:page-context',
  PAGE_CONTEXT_ENABLED: 'hchat:page-context-enabled',
  HIGHLIGHTS: 'hchat:highlights',
  HIGHLIGHT_INDEX: 'hchat:highlight-index',
  QUICK_ACTION: 'hchat:quick-action',
  FOLDERS: 'hchat:folders',
  TAGS: 'hchat:tags',
  PROMPTS: 'hchat:prompts',
  SHORTCUTS: 'hchat:shortcuts',
  PERSONAS: 'hchat:personas',
  ACTIVE_PERSONA: 'hchat:active-persona',
  SUMMARIES: 'hchat:summaries',
  LAST_WEBHOOK_ALERT: 'hchat:last-webhook-alert',
} as const

export type StorageKey = (typeof SK)[keyof typeof SK]
